PortfolioManager/Controllers/NewsController.cs
using PortfolioManager.CoreLogic;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PortfolioManager.Controllers
{
    public class NewsController : Controller
    {
        // GET: News
        public ActionResult GetTopNews()
        {
            var FetchNews = new NewsApi().getTopNews();
            return View(FetchNews);
        }

        
    }
}

PortfolioManager/Controllers/StockController.cs
using PortfolioManager.Models;
using PortfolioManager.ViewModels;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PortfolioManager.Controllers
{
    public class StockController : Controller
    {
        private ApplicationDbContext _content;

        public StockController()
        {
            _content = new ApplicationDbContext();
        }
        protected override void Dispose(bool disposing)
        {
            _content.Dispose();
        }
        // GET: Stock
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult GetTopStocks()
        {
            var stocks = new StockListViewModel { StockList = new List<EquityStock>
            {
                new EquityStock{ Symbol= "MSFT", OriginalPrice=73.9m},
                new EquityStock{ Symbol="AMD", OriginalPrice=13.5m}
            }
            };

            return View(stocks);
        }

        public ActionResult PortfolioList()
        {
            var customers = _content.Customers.Include(x=>x.CustomerPortfolio);
            return View(customers);
        }

        public ActionResult StockList(int id)
        {
            var customer = _content.Customers.Single(x => x.CustomerId == id);
            return View(customer.CustomerPortfolio);
        }
    }
}

PortfolioManager/Views/Shared/_Layout.cshtml
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    @Html.Partial("_NavBar")
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

PortfolioManager/Views/Shared/_NavBar.cshtml
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("Portfolio Manager", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Home", "Index", "Home")</li>
                <li>@Html.ActionLink("Customers", "CustomerList", "Customer")</li>
                <li>@Html.ActionLink("Portfolios", "PortfolioList", "Stock")</li>
                <li>@Html.ActionLink("Top News", "GetTopNews","News")</li>
            </ul>
            @Html.Partial("_LoginPartial")
        </div>
    </div>
</div>