PortfolioManager/Controllers/Api/TransactionController.cs
using PortfolioManager.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;

namespace PortfolioManager.Controllers.Api
{
    public class TransactionController : ApiController
    {
        private ApplicationDbContext _content;

        public TransactionController()
        {
            _content = new ApplicationDbContext();
        }

        protected override void Dispose(bool disposing)
        {
            _content.Dispose();
        }

        // GET /api/transaction
        public IHttpActionResult GetTransaction()
        {
            return Ok(_content.Transactions.OrderBy(x => x.TimeStamp).ToList());
        }
        // GET /api/transaction/1
        public IHttpActionResult GetTransaction(int id)
        {
            var transactions = _content.Transactions.Where(x => x.PortfolioId == id).ToList();

            if (transactions == null)
                return NotFound();

            return Ok(transactions);
        }

        // POST /api/transaction
        [HttpPost]
        public IHttpActionResult AddTransaction(Transaction transaction)
        {
            if (!ModelState.IsValid)
                return BadRequest();

            _content.Transactions.Add(transaction);
            _content.SaveChanges();
            return Ok(transaction);
        }
    }
}

PortfolioManager/Controllers/TransactionController.cs
using PortfolioManager.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;

namespace PortfolioManager.Controllers
{
    public class TransactionController : Controller
    {
        private ApplicationDbContext _content;

        public TransactionController()
        {
            _content = new ApplicationDbContext();
        }
        protected override void Dispose(bool disposing)
        {
            _content.Dispose();
        }
        // GET: Transaction
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add(Transaction transaction)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.PortfolioId = transaction.PortfolioId;
                return View("AddTransactionForm");
            }
            _content.Transactions.Add(transaction);
            _content.SaveChanges();

            return View("PortfolioList");
        }
        public ActionResult AddTransactionForm(int id)
        {
            ViewBag.PortfolioId = id;
            return View();
        }


        public ActionResult PortfolioList()
        {
            var customers = _content.Customers.Include(x => x.CustomerPortfolio);
            return View(customers);
        }
    }
}

PortfolioManager/Views/Transaction/AddTransactionForm.cshtml
@model PortfolioManager.Models.Transaction
@{
    ViewBag.Title = "AddTransactionForm";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Add Transaction Form</h2>
@Html.ValidationSummary()
@using (Html.BeginForm("Add", "Transaction"))
{
    <div class="form-group">
        @Html.LabelFor(m => m.PortfolioId)
        @Html.TextBoxFor(m => m.PortfolioId,
       new { @class = "form-control", @Value = ViewBag.PortfolioId, @readonly = "readonly"})
        @Html.ValidationMessageFor(m => m.PortfolioId)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Symbol)
        @Html.TextBoxFor(m => m.Symbol, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Symbol)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Quantity)
        @Html.TextBoxFor(m => m.Quantity, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Quantity)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Price)
        @Html.TextBoxFor(m => m.Price, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Price)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.TransactionType)
        @Html.TextBoxFor(m => m.TransactionType, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.TransactionType)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.TimeStamp)
        @Html.TextBoxFor(m => m.TimeStamp, new { @class = "form-control", @Value = DateTime.Now })
        @Html.ValidationMessageFor(m => m.TimeStamp)
    </div>
    @Html.AntiForgeryToken()
    <button type="submit" class="btn btn-primary">Save</button>
}

PortfolioManager/Views/Transaction/PortfolioList.cshtml
@model IEnumerable<PortfolioManager.Models.Customer>
@{
    ViewBag.Title = "PortfolioList";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Portfolio List</h2>

<table style="width:60%">
    <tr>
        <th>Customer Id</th>
        <th>Customer Name</th>
        <th>Portfolio Value</th>
    </tr>
    @foreach (var customer in Model)
    {
        <tr>
            <td>@customer.CustomerId</td>
            <td>@Html.ActionLink(@customer.CustomerName, "AddTransactionForm", "Transaction", new { id = @customer.CustomerPortfolio.PortfolioId }, null)</td>
            <td>@customer.CustomerPortfolio.GetPortfolioValue()</td>
        </tr>
    }
</table>